language: python

sudo: false

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django17
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19

install:
  - pip3 install tox

script:
  - tox -e $TOX_ENV
