language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django17
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
